export const StorageKey = {
    REMEMBER_ME: 'ONEZOL.COM:REMEMBER_ME',
    USER_STATUS: 'ONEZOL.COM:USER_STATUS',
    USER_TOKEN: 'ONEZOL.COM:USER_TOKEN',
    USER_ACCOUNT: 'ONEZOL.COM:USER_ACCOUNT',
}